# -*- coding: utf-8 -*-
"""gradio_client.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0WMzhwXrPU2-eqN2Zfn2rHlRgVfNu8S
"""

# ====== Imports ======
import gradio as gr
import requests
import json


# --- CONFIG ---
# !!! IMPORTANT: REPLACE THIS WITH YOUR DEPLOYED GCP FASTAPI URL !!!
API_HOST = "http://rag-api:8080"

# -----------------------
# UTILITY FUNCTIONS
# -----------------------
def can_connect(host: str, timeout: float = 5.0):
    """Checks if the external FastAPI service is reachable."""
    try:
        response = requests.get(host.rstrip("/"), timeout=timeout)
        return response.status_code == 200
    except Exception:
        return False

def call_query_index(host: str, query: str):
    """Calls the RAG index endpoint via POST request."""
    url = host.rstrip("/") + "/query_index"
    print(f"url: {url}")
    try:
        resp = requests.post(url, json={"query": query}, timeout=300)
    except requests.exceptions.RequestException as e:
        err = f"**Request Failed!** cannot connect to {url}. Error: {e}"
        return err, json.dumps({"error": str(e), "url": url}, indent=2)

    try:
        data = resp.json()
    except Exception:
        return f"**Invalid JSON Response** (Status: {resp.status_code}):\n{resp.text}", \
               json.dumps({"status_code": resp.status_code, "text": resp.text})

    if resp.status_code == 200:
        pretty_answer = data.get('index_response', 'No response found in index_response field')
        final_output = f"**RAG Agent Response**\n\n{pretty_answer}"
    else:
        final_output = f"**Server Error** (Status: {resp.status_code}): {data.get('detail', data)}"

    raw_json = json.dumps(data, indent=2)
    return final_output, raw_json

def call_get_branch_info(host: str, zip_code: str):
    """Calls the branch info endpoint via GET request."""
    url = host.rstrip("/") + "/get_branch_info"
    try:
        resp = requests.get(url, params={"zip_code": zip_code}, timeout=20)
    except requests.exceptions.RequestException as e:
        err = f"**Request Failed!** Cannot connect to {url}. Error: {e}"
        return err, json.dumps({'error': str(e), 'url': url}, indent=2)

    try:
        data = resp.json()
    except Exception:
        return f"**Invalid JSON Response** (Status {resp.status_code}):\n{resp.text}", \
               json.dumps({"status_code": resp.status_code, "text": resp.text}, indent=2)

    if resp.status_code == 200:
        pretty_address = data.get('branch_address', 'Branch address field not found in response.')
    else:
        pretty_address = f"**Server Error** (Status: {resp.status_code}): {data.get('detail', data)} "

    raw_json = json.dumps(data, indent=2)
    return pretty_address, raw_json

# -----------------------
# GRADIO HANDLERS
# -----------------------
def handle_query(query: str, host: str):
    if not query.strip():
        return "Please type a question.", gr.update(visible=False, value={})
    if not can_connect(host):
        return f"**Connection Error:** Cannot reach {host}.", gr.update(visible=False, value={})

    pretty_output, raw_output = call_query_index(host, query)
    # Ensure raw_output is a valid JSON dictionary for the gr.JSON component
    return pretty_output, gr.update(value=json.loads(raw_output))

def handle_branch(zip_code: str, host: str):
    if not zip_code.strip():
        return "Please provide zip code", gr.update(visible=False, value={})
    if not can_connect(host):
        return f"**Connection Error:** Cannot reach {host}.", gr.update(visible=False, value={})

    pretty_output, raw_output = call_get_branch_info(host, zip_code)
    # Ensure raw_output is a valid JSON dictionary for the gr.JSON component
    return pretty_output, gr.update(value=json.loads(raw_output))

# -----------------------
# GRADIO UI
# -----------------------
with gr.Blocks(title='URA Bank - RAG Agent UI Client') as demo:
    gr.Markdown("""
    # URA Bank - RAG AI Agent Client (Gradio)
    Connects to your FastAPI server via public URL.

    **Instructions:**
    1. Start your FastAPI RAG server on GCP (using the Docker container).
    2. Ensure the Host below is your deployed FastAPI URL.
    """)

    api_host = gr.Textbox(label="FastAPI Host (Full URL)", value=API_HOST, scale=3)
    show_raw_checkbox = gr.Checkbox(label="Show Raw JSON Response", value=False, scale=0)

    with gr.Tabs():

        with gr.TabItem("RAG Knowledge Query"):
            rag_query_input = gr.Textbox(
                label="RAG Query",
                placeholder="e.g., What are the terms for the Unsecured Personal Loan?",
                lines=3
            )
            rag_button = gr.Button("Get RAG Answer", variant="primary")
            rag_output = gr.Markdown(label='RAG Agent Answer')
            rag_raw_output = gr.JSON(label="Raw JSON Response", visible=False, value={})

            rag_button.click(
                fn=handle_query,
                inputs=[rag_query_input, api_host],
                outputs=[rag_output, rag_raw_output]
            )

        with gr.TabItem("Branch Locator Tool"):
            zip_code_input = gr.Textbox(
                label="Enter Zip Code",
                placeholder="e.g., 500034",
                lines=1
            )
            branch_button = gr.Button("Find Nearest Branch", variant="secondary")
            branch_output = gr.Markdown(label="Nearest Branch Address")
            branch_raw_output = gr.JSON(label="Raw JSON Response", visible=False, value={})

            branch_button.click(
                fn=handle_branch,
                inputs=[zip_code_input, api_host],
                outputs=[branch_output, branch_raw_output]
            )

        def update_raw_visibility(show):
            return gr.update(visible=show), gr.update(visible=show)

        show_raw_checkbox.change(
            fn=update_raw_visibility,
            inputs=[show_raw_checkbox],
            outputs=[rag_raw_output, branch_raw_output]
        )

if __name__ == '__main__':
    # You run this client script locally or on a separate machine/service.
    demo.launch(server_name="0.0.0.0",  # <--- CRITICAL FOR DOCKER
        server_port=7860)