{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPrO9XWq/jjkvf4Y86mtSp6",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/jerryab31/Dockerized-RAG-API-Gradio-UI-Project-Setup/blob/main/client_app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "rJA5lZ2y_-E_"
      },
      "outputs": [],
      "source": [
        "# ====== Imports ======\n",
        "import gradio as gr\n",
        "import requests\n",
        "import json\n",
        "\n",
        "\n",
        "# --- CONFIG ---\n",
        "# !!! IMPORTANT: REPLACE THIS WITH YOUR DEPLOYED GCP FASTAPI URL !!!\n",
        "API_HOST = \"http://rag-api:8080\"\n",
        "\n",
        "# -----------------------\n",
        "# UTILITY FUNCTIONS\n",
        "# -----------------------\n",
        "def can_connect(host: str, timeout: float = 5.0):\n",
        "    \"\"\"Checks if the external FastAPI service is reachable.\"\"\"\n",
        "    try:\n",
        "        response = requests.get(host.rstrip(\"/\"), timeout=timeout)\n",
        "        return response.status_code == 200\n",
        "    except Exception:\n",
        "        return False\n",
        "\n",
        "def call_query_index(host: str, query: str):\n",
        "    \"\"\"Calls the RAG index endpoint via POST request.\"\"\"\n",
        "    url = host.rstrip(\"/\") + \"/query_index\"\n",
        "    print(f\"url: {url}\")\n",
        "    try:\n",
        "        resp = requests.post(url, json={\"query\": query}, timeout=900)\n",
        "    except requests.exceptions.RequestException as e:\n",
        "        err = f\"**Request Failed!** cannot connect to {url}. Error: {e}\"\n",
        "        return err, json.dumps({\"error\": str(e), \"url\": url}, indent=2)\n",
        "\n",
        "    try:\n",
        "        data = resp.json()\n",
        "    except Exception:\n",
        "        return f\"**Invalid JSON Response** (Status: {resp.status_code}):\\n{resp.text}\", \\\n",
        "               json.dumps({\"status_code\": resp.status_code, \"text\": resp.text})\n",
        "\n",
        "    if resp.status_code == 200:\n",
        "        pretty_answer = data.get('index_response', 'No response found in index_response field')\n",
        "        final_output = f\"**RAG Agent Response**\\n\\n{pretty_answer}\"\n",
        "    else:\n",
        "        final_output = f\"**Server Error** (Status: {resp.status_code}): {data.get('detail', data)}\"\n",
        "\n",
        "    raw_json = json.dumps(data, indent=2)\n",
        "    return final_output, raw_json\n",
        "\n",
        "def call_get_branch_info(host: str, zip_code: str):\n",
        "    \"\"\"Calls the branch info endpoint via GET request.\"\"\"\n",
        "    url = host.rstrip(\"/\") + \"/get_branch_info\"\n",
        "    try:\n",
        "        resp = requests.get(url, params={\"zip_code\": zip_code}, timeout=20)\n",
        "    except requests.exceptions.RequestException as e:\n",
        "        err = f\"**Request Failed!** Cannot connect to {url}. Error: {e}\"\n",
        "        return err, json.dumps({'error': str(e), 'url': url}, indent=2)\n",
        "\n",
        "    try:\n",
        "        data = resp.json()\n",
        "    except Exception:\n",
        "        return f\"**Invalid JSON Response** (Status {resp.status_code}):\\n{resp.text}\", \\\n",
        "               json.dumps({\"status_code\": resp.status_code, \"text\": resp.text}, indent=2)\n",
        "\n",
        "    if resp.status_code == 200:\n",
        "        pretty_address = data.get('branch_address', 'Branch address field not found in response.')\n",
        "    else:\n",
        "        pretty_address = f\"**Server Error** (Status: {resp.status_code}): {data.get('detail', data)} \"\n",
        "\n",
        "    raw_json = json.dumps(data, indent=2)\n",
        "    return pretty_address, raw_json\n",
        "\n",
        "# -----------------------\n",
        "# GRADIO HANDLERS\n",
        "# -----------------------\n",
        "def handle_query(query: str, host: str):\n",
        "    if not query.strip():\n",
        "        return \"Please type a question.\", gr.update(visible=False, value={})\n",
        "    if not can_connect(host):\n",
        "        return f\"**Connection Error:** Cannot reach {host}.\", gr.update(visible=False, value={})\n",
        "\n",
        "    pretty_output, raw_output = call_query_index(host, query)\n",
        "    # Ensure raw_output is a valid JSON dictionary for the gr.JSON component\n",
        "    return pretty_output, gr.update(value=json.loads(raw_output))\n",
        "\n",
        "def handle_branch(zip_code: str, host: str):\n",
        "    if not zip_code.strip():\n",
        "        return \"Please provide zip code\", gr.update(visible=False, value={})\n",
        "    if not can_connect(host):\n",
        "        return f\"**Connection Error:** Cannot reach {host}.\", gr.update(visible=False, value={})\n",
        "\n",
        "    pretty_output, raw_output = call_get_branch_info(host, zip_code)\n",
        "    # Ensure raw_output is a valid JSON dictionary for the gr.JSON component\n",
        "    return pretty_output, gr.update(value=json.loads(raw_output))\n",
        "\n",
        "# -----------------------\n",
        "# GRADIO UI\n",
        "# -----------------------\n",
        "with gr.Blocks(title='URA Bank - RAG Agent UI Client') as demo:\n",
        "    gr.Markdown(\"\"\"\n",
        "    # URA Bank - RAG AI Agent Client (Gradio)\n",
        "    Connects to your FastAPI server via public URL.\n",
        "\n",
        "    **Instructions:**\n",
        "    1. Start your FastAPI RAG server on GCP (using the Docker container).\n",
        "    2. Ensure the Host below is your deployed FastAPI URL.\n",
        "    \"\"\")\n",
        "\n",
        "    api_host = gr.Textbox(label=\"FastAPI Host (Full URL)\", value=API_HOST, scale=3)\n",
        "    show_raw_checkbox = gr.Checkbox(label=\"Show Raw JSON Response\", value=False, scale=0)\n",
        "\n",
        "    with gr.Tabs():\n",
        "\n",
        "        with gr.TabItem(\"RAG Knowledge Query\"):\n",
        "            rag_query_input = gr.Textbox(\n",
        "                label=\"RAG Query\",\n",
        "                placeholder=\"e.g., What are the terms for the Unsecured Personal Loan?\",\n",
        "                lines=3\n",
        "            )\n",
        "            rag_button = gr.Button(\"Get RAG Answer\", variant=\"primary\")\n",
        "            rag_output = gr.Markdown(label='RAG Agent Answer')\n",
        "            rag_raw_output = gr.JSON(label=\"Raw JSON Response\", visible=False, value={})\n",
        "\n",
        "            rag_button.click(\n",
        "                fn=handle_query,\n",
        "                inputs=[rag_query_input, api_host],\n",
        "                outputs=[rag_output, rag_raw_output]\n",
        "            )\n",
        "\n",
        "        with gr.TabItem(\"Branch Locator Tool\"):\n",
        "            zip_code_input = gr.Textbox(\n",
        "                label=\"Enter Zip Code\",\n",
        "                placeholder=\"e.g., 500034\",\n",
        "                lines=1\n",
        "            )\n",
        "            branch_button = gr.Button(\"Find Nearest Branch\", variant=\"secondary\")\n",
        "            branch_output = gr.Markdown(label=\"Nearest Branch Address\")\n",
        "            branch_raw_output = gr.JSON(label=\"Raw JSON Response\", visible=False, value={})\n",
        "\n",
        "            branch_button.click(\n",
        "                fn=handle_branch,\n",
        "                inputs=[zip_code_input, api_host],\n",
        "                outputs=[branch_output, branch_raw_output]\n",
        "            )\n",
        "\n",
        "        def update_raw_visibility(show):\n",
        "            return gr.update(visible=show), gr.update(visible=show)\n",
        "\n",
        "        show_raw_checkbox.change(\n",
        "            fn=update_raw_visibility,\n",
        "            inputs=[show_raw_checkbox],\n",
        "            outputs=[rag_raw_output, branch_raw_output]\n",
        "        )\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    # You run this client script locally or on a separate machine/service.\n",
        "    demo.launch(server_name=\"0.0.0.0\",  # <--- CRITICAL FOR DOCKER\n",
        "        server_port=7860)"
      ]
    }
  ]
}
