FROM python:3.12-slim

WORKDIR /app

COPY requirements_gradio.txt /app/

RUN pip install --no-cache-dir -r requirements_gradio.txt

COPY client_app.py /app/

EXPOSE 7860


CMD ["python","client_app.py"]
